[docusaurus]
title = "Avalog"
tagline = "The premium avatar catalog editor"
url = "https://loneka.com/"
baseUrl = "/avalog"
favicon = "svg/LogoGlyph.svg"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Simplicity ğŸ˜Œ"
description = "Avalog prioritizes your experience, and doesn't bombard you with branding, sign-up, or clunk."

[[home.features]]
title = "Customization ğŸ–Œï¸"
description = "Comprehensive theming properties allow you to match your game's mood and style with ease."

[[home.features]]
title = "Monetization ğŸ’¸"
description = "Earn 40% on all items sold in your game, and list your own UGC items."

[footer]
style = "light"
copyright = "Copyright Â© 2025 Avafe. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Loneka"

[[footer.links.items]]
label = "Home"
href = "https://loneka.com"

[navbar]
title = ""

[navbar.logo]
alt = "Avalog"
src = "/svg/LogoDark.svg"
srcDark = "/svg/Logo.svg"
